# Generated by Django 2.0.4 on 2018-07-06 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 7, 6, 5, 2, 14, 102503, tzinfo=utc))),
                ('published_date', models.DateTimeField(verbose_name='published time')),
            ],
        ),
    ]
