# Generated by Django 2.0.4 on 2018-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, help_text='simple description txt', max_length=100, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='null', help_text='one word for title alias', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
    ]
