# Generated by Django 2.0.4 on 2018-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180721_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
        migrations.AlterField(
            model_name='board',
            name='text',
            field=models.TextField(verbose_name='CONTENT'),
        ),
    ]
